version: '3.8'

services:
  flashcards:
    image: 192.168.50.20:5000/flashcards:latest
    ports:
      - "8080:3000"
    environment:
      - FIREBASE_SERVICE_ACCOUNT=${FIREBASE_SERVICE_ACCOUNT}
    restart: unless-stopped